export const allTypes: string[] = [
    "Academic Study & Paper",
    "Annual Survey Report",
    "Article",
    "Assessment Tool",
    "Blog Post",
    "Books",
    "Case studies",
    "Guidance Document",
    "Images & Infographics",
    "Lists of Useful Links",
    "Online Course",
    "Online Training",
    "Podcast",
    "Review & Analysis",
    "Service providers",
    "Shared Best Practices Document",
    "Source of Resources",
    "Templates",
    "Theme Specific Report",
    "Tips and Recommendations",
    "Toolkits",
    "Topic Specific Database Source",
    "Training Document",
    "Training Resources",
    "Video",
    "Webinar",
    "White Paper"
]

export const allIndustries: string[] = [
    "Arms, defence & military",
    "Banking & finance",
    "Civilian aerospace",
    "Consumer services",
    "Education",
    "Fisheries",
    "Forestry",
    "Government entities",
    "Heavy manufacturing",
    "Information technology",
    "Light manufacturing",
    "Mining",
    "NGO – Not-for-profit",
    "Oil& gas",
    "Pharmaceutical & healthcare",
    "Power generation & transmission",
    "Public works contracts & Construction",
    "Real estate, property, legal & business services",
    "Telecommunications",
    "Transportation & storage",
    "Utilities"
]

export const allThemes: string[] = [
    "Artificial Intelligence & Machine Learning in Compliance",
    "Behavioral Ethics",
    "Benchmarking & Evaluation",
    "Best Practices",
    "Code of Conduct",
    "Commercial Service Providers",
    "Compliance Program Testing & Benchmarking",
    "Components of an Ethics & Compliance Program",
    "Confidential Reporting (Whistleblowing)",
    "Corruption",
    "Cyber Security",
    "Data Analytics",
    "Designing & Implementing an Ethics & Compliance Program",
    "Due Diligence & Enhanced Due Diligence",
    "ESG - Climate Change & Environmental Ethics",
    "ESG - Diversity, Equity & Inclusion (DEI)",
    "ESG - Human Rights Due Diligence",
    "ESG - Supply Chain Transparency",
    "ESG - Other",
    "Elements of an Ethics and Compliance Program",
    "Ethics & Integrity",
    "Ethics and Compliance Function",
    "Fraud & Other Financial Crime Risks",
    "Free & Almost Free Resources",
    "General ABC Terms & Libraries",
    "Geopolitical Risks and Sanctions Compliance",
    "Gift & Entertainment Risks",
    "Governance",
    "IT Tools that Support Compliance Function",
    "Internal Investigations",
    "Leadership and Governance",
    "Lessons Learned from the Front Lines",
    "M&A and JV Risks",
    "Money Laundering & Terrorism Financing",
    "Monitoring and Continuous Improvements",
    "Organisational Culture",
    "Policies",
    "Procedures & Financial Controls",
    "Relevant Laws & Regs",
    "Risk Assessments",
    "Supply Chain Transparency",
    "Third Party Due Diligence",
    "Training & Communication"
]

export const allOrganizations: string[] = [
    "Advocacy",
    "Civil Society",
    "Commercial",
    "Institute",
    "International body",
    "NGO",
    "Not-for-profit",
    "Professional body/organization",
    "Public / Government",
    "University"
]